TITLE_ID = TETRIS001
TARGET   = tetris
OBJS     = Block.o   Shape.o   GameBoard.o   DrawSdl.o   GameSdl.o main.o

LIBS =  -lSDL2 -lSceAudio_stub -lvita2d -lSceDisplay_stub -lSceGxm_stub \
	-lSceSysmodule_stub -lSceCtrl_stub -lScePgf_stub \
	-lSceCommonDialog_stub -lfreetype -lpng -ljpeg -lz -lm -lc 

PREFIX  = arm-vita-eabi
#CC      = $(PREFIX)-gcc
CC      = $(PREFIX)-g++
CFLAGS  = -Wl,-q -Wall -fno-lto
CXXFLAGS= -Wl,-q -Wall -fno-lto -lSDL2 -D__SDL20__

ASFLAGS = $(CFLAGS)

all: $(TARGET).vpk

%.vpk: eboot.bin
	vita-mksfoex -s TITLE_ID=$(TITLE_ID) "$(TARGET)" param.sfo
	vita-pack-vpk -s param.sfo -b eboot.bin $@

eboot.bin: $(TARGET).velf
	vita-make-fself -s $< $@

%.velf: %.elf
	vita-elf-create $< $@

$(TARGET).elf: $(OBJS)
	$(CC) $(CFLAGS) $^ $(LIBS) -o $@

%.o : %.cpp 
	$(PREFIX)-g++ -c $(CXXFLAGS) $(LIBS) -o $@ $<

%.o: %.png
	$(PREFIX)-ld -r -b binary -o $@ $^

clean:
	@rm -rf $(TARGET).vpk $(TARGET).velf $(TARGET).elf $(OBJS) \
		eboot.bin param.sfo

vpksend: $(TARGET).vpk
	curl -T $(TARGET).vpk ftp://$(PSVITAIP):1337/ux0:/Vpk/
	@echo "Sent."

send: eboot.bin
	curl -T eboot.bin ftp://$(PSVITAIP):1337/ux0:/app/$(TITLE_ID)/
	@echo "Sent."
